### ISSUE TITLE
Building offloaded_doublevadd_publisher failed

### ISSUE THREAD

**Issue by surender009** [ros-acceleration/acceleration_examples#12]
#steps followed from KRS Documentation and trying to build **offloaded_doublevadd_publisher** package, below is the error log.

surender@xhdsurender41:/scratch/krs_ws$ colcon build --build-base=build-kv260 --install-base=install-kv260 --merge-install --mixin kv260 --packages-select ament_vitis ros2acceleration offloaded_doublevadd_publisher

Starting >>> ament_vitis
Starting >>> ros2acceleration
Finished <<< ament_vitis [0.55s]
Starting >>> offloaded_doublevadd_publisher
[0.998s] WARNING:colcon.colcon_core.shell:The following packages are in the workspace but haven't been built:
- vitis_common
They are being used from the following locations instead:
- /scratch/krs_ws/install
To suppress this warning ignore these packages in the workspace:
--packages-ignore vitis_common
Finished <<< ros2acceleration [0.57s]
**--- stderr: offloaded_doublevadd_publisher
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "Findvitis_common.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "vitis_common", but CMake did not find one.

  Could not find a package configuration file provided by "vitis_common" with
  any of the following names:

    vitis_commonConfig.cmake
    vitis_common-config.cmake

  Add the installation prefix of "vitis_common" to CMAKE_PREFIX_PATH or set
  "vitis_common_DIR" to a directory containing one of the above files.  If
  "vitis_common" provides a separate development package or SDK, be sure it
  has been installed.

---
Failed   <<< offloaded_doublevadd_publisher [0.75s, exited with code 1]**

Summary: 2 packages finished [1.47s]
  1 package failed: offloaded_doublevadd_publisher
  1 package had stderr output: offloaded_doublevadd_publisher

**Comment by vmayoral** [comment]
@surender009, the content above is very hard to understand. Please use [proper Markdown syntax](https://www.markdownguide.org/basic-syntax/). 

From the outlook, you're missing `vitis_common` package in your workspace. Include it and don't force particular packages (with `--packages-select ament_vitis ros2acceleration offloaded_doublevadd_publisher` flag). Build them all and report back with your result if you still struggle with it. 

**NOTE**: Make sure you're using the `0.2.0` branch of `acceleration_examples` as well please. That's what's released in KRS `alpha`. Also, @jasvinderkhurana, might be able to help since we just reviewed something similar today.

**Comment by jasvinderkhurana** [comment]
@vmayoral @surender009 ,

I also faced similar problem and building vitis_common package resolved the problem use below command:
```
colcon build --build-base=build-kv260 --install-base=install-kv260 --merge-install --mixin kv260 --packages-select vitis_common
```

Please check and let me know if the issue gets resolved at your end

**Comment by vmayoral** [comment]
Are we good in here @surender009? Do you need more assistance?

**Comment by surender009** [comment]
@vmayoral we can close this ticket

**Comment by vmayoral** [comment]
Thanks @surender009!
