### ISSUE TITLE
Some examples doesn't build

### ISSUE THREAD

**Issue by pimartos** [ros-acceleration/acceleration_examples#5]
Hi,
I was triying to build the examples, but the build fails due to a missing vitis_common package.
I think that the problem is that in the install instructions (https://xilinx.github.io/KRS/sphinx/build/html/docs/install.html), in the krs_alpha.repos file, the vitis_common repository is missing.
I cloned it manually and now the examples build, so is necessary to add vitis_common repository to the krs_alpha.repos file

regards,
Pedro

**Comment by vmayoral** [comment]
Thanks for this @pimartos, it's been addressed at https://github.com/Xilinx/KRS/issues/10. This issue was raised [a few days ago](https://github.com/Xilinx/KRS/issues/10#issue-1012277531), sorry it took Xilinx took few days to fix it.

It's been fixed now and you can find the latest version of the repos at https://github.com/Xilinx/KRS/blob/main/krs.repos. Do feel free to raise issues if you encounter other problems!
